pipeline {
  agent any

  stages {
    stage('Clone') {
      steps {
        git 'https://github.com/Hardik2102/Nodejs-cicd.git'
      }
    }

    stage('Build Docker Image') {
      steps {
        sh 'docker build -t nodejs-app .'
      }
    }

    stage('Deploy to Backend') {
      steps {
        // Use the SSH key stored in Jenkins Credentials (ID = 'my-ssh-key')
        sshagent(['my-ssh-key']) {
          sh 'scp -o StrictHostKeyChecking=no docker-compose.yml ubuntu@3.82.142.194:/home/ubuntu/'
          sh 'ssh -o StrictHostKeyChecking=no ubuntu@3.82.142.194 "docker-compose up -d"'
        }
      }
    }
  }
}
