pipeline {
  agent any

  stages {
    stage('Clone') {
      steps {
        git 'https://github.com/Hardik2102/Nodejs-cicd.git'
      }
    }
    stage('Build Docker Image') {
      steps {
        sh 'docker build -t nodejs-app .'
      }
    }
    stage('Deploy to Backend') {
      steps {
        sh 'scp -i ~/.ssh/test.pem docker-compose.yml ubuntu@3.82.142.194:/home/ubuntu/'
        sh 'ssh -i ~/.ssh/test.pem ubuntu@3.82.142.194 "docker-compose up -d"'
      }
    }
  }
}
